Vagrant.configure("2") do |config|
    config.vm.define "web0" do |web0|
      web0.vm.box = "ubuntu/jammy64"
      web0.vm.hostname = "web0"
      web0.vm.network "private_network", ip: "192.168.56.41"
    end


    config.vm.define "web1" do |web1|
      web1.vm.box = "ubuntu/jammy64"
      web1.vm.hostname = "web1"
      web1.vm.network "private_network", ip: "192.168.56.42"
    end


    config.vm.define "db0" do |db0|
      db0.vm.box = "eurolinux-vagrant/centos-stream-9"
      db0.vm.hostname = "db0"
      db0.vm.network "private_network", ip: "192.168.56.43"
      db0.vm.provision "shell", inline: <<-SHELL
        ip add show
      SHELL
    end
end
